$(document).ready(function(){
    $(".design-image").click(function(){
        $("#design").toggle();
    })
})
$(document).ready(function(){
    $(".service-image").click(function(){
        $("#services").toggle();
    })
})
